# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f34f9a777604f4804b61e82d6536ed08759de66d86c2e271850c686bc46784c71dc57480c9213d67452b19563504cb6ebb72bfa137f8768348d66e8aa2854358

test:
  secret_key_base: a118746436c5dea29015fbef30efd7862ddad10d67169b11a9fa9259b769519be0e71448df631dd69e86c335a6dbfa10f76470a9e5aef10990ddffee764d8b33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
